### ISSUE TITLE
Make the index.html mobile and SEO friendly add related tags

### ISSUE THREAD

**Issue by tanaypratap** [tanaypratap/polaris#13]
## Requirement
The index.html is currently bare-bones. However, to be used in production it needs tags for viewport, it needs tag for twitter, facebook, apple, site-url etc. 

## Tasks
1. Add tags which make it mobile friendly, and SEO friendly. If website name is required you can use a placeholder i.e. https://polaris2018.com
2. Add a seo-mobile-friendly.md in docs folder giving little bit of explanation about the meta tags being used so that it can help future users.

## Please Note
This issue is being tagged as `hacktoberfest` and thus seeing a lot of traffic. If you're going to work on it and raise a PR, please comment. First preference to merge the project will be given to the first comment. However, the person has 24 hours of time to raise the PR. After that, the issue will be open for contribution again.

**Comment by abhishekmayank** [comment]
I will do it

**Comment by digilou** [comment]
@abhishekmayank Are you working on this?
