### ISSUE TITLE
PWA Checklist: Create manifest.json

### ISSUE THREAD

**Issue by tanaypratap** [tanaypratap/polaris#15]
## Requirement
Manifest.json file is needed for app to be treated as PWA. 

## Tasks
1. Create manifest.json file. See examples here: 
 - https://developer.mozilla.org/en-US/docs/Web/Manifest
 - https://developers.google.com/web/fundamentals/web-app-manifest/

2. Add manifest.json file to index.html
3. Run app in chrome, use Lighthouse to check if it passes manifest test. Post a screenshot in your PR description.
Since, icons are not there currently to put in manifest.json feel free to use one image for all resolutions. Issue https://github.com/tanaypratap/polaris-2018/issues/14  can be tracked for getting icons also incorporated.

## Please Note
This issue is being tagged as `hacktoberfest` and thus seeing a lot of traffic. If you're going to work on it and raise a PR, please comment. First preference to merge the project will be given to the first comment. However, the person has 24 hours of time to raise the PR. After that, the issue will be open for contribution again.

**Comment by digilou** [comment]
Hi @tanaypratap, can I give this a go for hacktoberfest? A manifest file is a good idea for any PWA.

**Comment by tanaypratap** [comment]
Please go ahead. Since you're doing both the PRs it would be easy for you to use your icons. Thanks for picking this up.

**Comment by digilou** [comment]
@tanaypratap Could you tell me how to run your server. I find each setup a bit different, and I've just recently come from Node projects.

**Comment by tanaypratap** [comment]
Ack. Writing the instructions.

**Comment by tanaypratap** [comment]
@digilou here you go. https://github.com/tanaypratap/polaris-2018#running-the-client-and-server 
Let me know if I missed something

**Comment by digilou** [comment]
@tanaypratap Thank you! I'll try this tonight when I get home. I was close, but that clears it up for me.

**Comment by digilou** [comment]
@tanaypratap This is what I see:
<img width="333" alt="Test Page Online" src="https://user-images.githubusercontent.com/8865558/46558756-a85d3680-c89a-11e8-9c80-c837ee5bbb9a.png">

I see that's the message sent from the server in the server file. Maybe I need to add something to `localhost:6789` to see the index?

**Comment by tanaypratap** [comment]
To see the index you need to run the client. See the index.html file in client folder. That is where you need to add the manifest file.

**Comment by IstiaqueSiddiqi** [comment]
Hi @tanaypratap 

Is this issue still open ?
