### ISSUE TITLE
Setup Testing for Server Side: Express

### ISSUE THREAD

**Issue by tanaypratap** [tanaypratap/polaris#2]
I am unsure as to which framework to choose for Testing for express. Need ideas, and few example tests to be setup on the server side.

I see three work items for this issue:
1. Which framework to chose and why we chose that? Put arguments of choice in a .md file.
2. Create few dummy APIs on the server side and write example tests for it.
3. Create an npm script entry to run tests.

**Comment by ShekharNain** [comment]
Working on it.
