### ISSUE TITLE
Add support for TSLint

### ISSUE THREAD

**Issue by tanaypratap** [tanaypratap/polaris#3]
1. Support for TSLint.
2. .vscode settings to make it easy for vscode users to get tslint.
3. Add documentation on how to get tslint working for everyone working on the project.
4. create npm script entry for fixing common tslint errors. `"format": "tsint --fix .",`

**Comment by js-sapphire** [comment]
I will work on this

**Comment by tanaypratap** [comment]
@js-sapphire any update on this?
