### ISSUE TITLE
Add Jest Support for testing React App

### ISSUE THREAD

**Issue by tanaypratap** [tanaypratap/polaris#8]
1. Add Jest
2. Make sure it works in TypeScript
3. Add script entry in package.json to run tests
4. Add docs how-to-add-tests.md for future users to add new tests and things to keep in mind, troubleshooting tips and corner cases to take care.

Note: In case you publish a blog around it, please provide a link to it later creating a new PR again.

**Comment by cfsbsi** [comment]
I can help with this :)

**Comment by tanaypratap** [comment]
Hi @cfsbsi there's already one guy who has pinged me for this. He's raising a PR. I think he forgot to comment. Would you mind helping me in reviewing his PR? I have few other issues which I am creating around this project.

**Comment by cfsbsi** [comment]
ok, np, I will try to do another issue, thanks

**Comment by tanaypratap** [comment]
@cfsbsi do you mind reviewing this PR? https://github.com/tanaypratap/polaris-2018/pull/16

**Comment by cfsbsi** [comment]
@tanaypratap done, It's look ok for me
